import json

data = '''
{  
   'PlacePrices':[  
      {  
         'Id':'MN',
         'Name':'Mongolia',
         'DirectPrice':395,
         'TripUrl':None
      },
      {  
         'Id':'TH',
         'Name':'Thailand',
         'DirectPrice':260,
         'IndirectPrice':201,
         'TripUrl':None
      },
      {  
         'Id':'SG',
         'Name':'Singapore',
         'DirectPrice':328,
         'TripUrl':None
      },
      {  
         'Id':'TW',
         'Name':'Taiwan',
         'DirectPrice':177,
         'IndirectPrice':166,
         'TripUrl':None
      },
      {  
         'Id':'VN',
         'Name':'Vietnam',
         'DirectPrice':153,
         'TripUrl':None
      },
      {  
         'Id':'PH',
         'Name':'Philippines',
         'DirectPrice':146,
         'TripUrl':None
      },
      {  
         'Id':'TR',
         'Name':'Turkey',
         'DirectPrice':546,
         'IndirectPrice':514,
         'TripUrl':None
      },
      {  
         'Id':'ID',
         'Name':'Indonesia',
         'DirectPrice':395,
         'IndirectPrice':241,
         'TripUrl':None
      },
      {  
         'Id':'MO',
         'Name':'Macau',
         'DirectPrice':303,
         'IndirectPrice':203,
         'TripUrl':None
      },
      {  
         'Id':'MY',
         'Name':'Malaysia',
         'DirectPrice':257,
         'IndirectPrice':245,
         'TripUrl':None
      },
      {  
         'Id':'HK',
         'Name':'Hong Kong',
         'DirectPrice':145,
         'TripUrl':None
      },
      {  
         'Id':'KH',
         'Name':'Cambodia',
         'DirectPrice':353,
         'IndirectPrice':243,
         'TripUrl':None
      },
      {  
         'Id':'MM',
         'Name':'Myanmar',
         'DirectPrice':465,
         'IndirectPrice':235,
         'TripUrl':None
      },
      {  
         'Id':'QA',
         'Name':'Qatar',
         'DirectPrice':1471,
         'IndirectPrice':750,
         'TripUrl':None
      },
      {  
         'Id':'EG',
         'Name':'Egypt',
         'IndirectPrice':579,
         'TripUrl':None
      },
      {  
         'Id':'ET',
         'Name':'Ethiopia',
         'DirectPrice':890,
         'IndirectPrice':851,
         'TripUrl':None
      },
      {  
         'Id':'IL',
         'Name':'Israel',
         'DirectPrice':793,
         'IndirectPrice':536,
         'TripUrl':None
      },
      {  
         'Id':'PF',
         'Name':'French Polynesia',
         'IndirectPrice':1723,
         'TripUrl':None
      },
      {  
         'Id':'GU',
         'Name':'Guam',
         'DirectPrice':302,
         'TripUrl':None
      },
      {  
         'Id':'NZ',
         'Name':'New Zealand',
         'DirectPrice':793,
         'IndirectPrice':446,
         'TripUrl':None
      },
      {  
         'Id':'BR',
         'Name':'Brazil',
         'IndirectPrice':740,
         'TripUrl':None
      },
      {  
         'Id':'PW',
         'Name':'Palau',
         'DirectPrice':468,
         'IndirectPrice':413,
         'TripUrl':None
      },
      {  
         'Id':'CA',
         'Name':'Canada',
         'DirectPrice':530,
         'IndirectPrice':392,
         'TripUrl':None
      },
      {  
         'Id':'MX',
         'Name':'Mexico',
         'DirectPrice':0,
         'IndirectPrice':604,
         'TripUrl':None
      },
      {  
         'Id':'IR',
         'Name':'Iran',
         'IndirectPrice':365,
         'TripUrl':None
      },
      {  
         'Id':'AE',
         'Name':'United Arab Emirates',
         'DirectPrice':568,
         'IndirectPrice':394,
         'TripUrl':None
      },
      {  
         'Id':'US',
         'Name':'United States',
         'DirectPrice':0,
         'IndirectPrice':335,
         'TripUrl':None
      },
      {  
         'Id':'MU',
         'Name':'Mauritius',
         'IndirectPrice':752,
         'TripUrl':None
      },
      {  
         'Id':'AU',
         'Name':'Australia',
         'DirectPrice':715,
         'IndirectPrice':384,
         'TripUrl':None
      },
      {  
         'Id':'CU',
         'Name':'Cuba',
         'IndirectPrice':626,
         'TripUrl':None
      },
      {  
         'Id':'CN',
         'Name':'China',
         'DirectPrice':135,
         'TripUrl':None
      },
      {  
         'Id':'IN',
         'Name':'India',
         'DirectPrice':629,
         'IndirectPrice':329,
         'TripUrl':None
      },
      {  
         'Id':'MV',
         'Name':'Maldives',
         'IndirectPrice':366,
         'TripUrl':None
      },
      {  
         'Id':'KR',
         'Name':'South Korea',
         'DirectPrice':46,
         'TripUrl':None
      },
      {  
         'Id':'UZ',
         'Name':'Uzbekistan',
         'DirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KZ',
         'Name':'Kazakhstan',
         'DirectPrice':577,
         'TripUrl':None
      },
      {  
         'Id':'JP',
         'Name':'Japan',
         'DirectPrice':139,
         'TripUrl':None
      },
      {  
         'Id':'PA',
         'Name':'Panama',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GE',
         'Name':'Georgia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'PK',
         'Name':'Pakistan',
         'IndirectPrice':711,
         'TripUrl':None
      },
      {  
         'Id':'LK',
         'Name':'Sri Lanka',
         'DirectPrice':720,
         'IndirectPrice':417,
         'TripUrl':None
      },
      {  
         'Id':'RU',
         'Name':'Russia',
         'DirectPrice':178,
         'TripUrl':None
      },
      {  
         'Id':'PL',
         'Name':'Poland',
         'DirectPrice':665,
         'IndirectPrice':532,
         'TripUrl':None
      },
      {  
         'Id':'FI',
         'Name':'Finland',
         'DirectPrice':717,
         'IndirectPrice':454,
         'TripUrl':None
      },
      {  
         'Id':'AT',
         'Name':'Austria',
         'DirectPrice':611,
         'IndirectPrice':487,
         'TripUrl':None
      },
      {  
         'Id':'ES',
         'Name':'Spain',
         'DirectPrice':622,
         'IndirectPrice':435,
         'TripUrl':None
      },
      {  
         'Id':'SE',
         'Name':'Sweden',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'DK',
         'Name':'Denmark',
         'IndirectPrice':546,
         'TripUrl':None
      },
      {  
         'Id':'ZA',
         'Name':'South Africa',
         'IndirectPrice':532,
         'TripUrl':None
      },
      {  
         'Id':'IT',
         'Name':'Italy',
         'DirectPrice':500,
         'IndirectPrice':383,
         'TripUrl':None
      },
      {  
         'Id':'HU',
         'Name':'Hungary',
         'IndirectPrice':461,
         'TripUrl':None
      },
      {  
         'Id':'GR',
         'Name':'Greece',
         'IndirectPrice':467,
         'TripUrl':None
      },
      {  
         'Id':'NL',
         'Name':'Netherlands',
         'DirectPrice':559,
         'IndirectPrice':458,
         'TripUrl':None
      },
      {  
         'Id':'BE',
         'Name':'Belgium',
         'IndirectPrice':463,
         'TripUrl':None
      },
      {  
         'Id':'CH',
         'Name':'Switzerland',
         'IndirectPrice':411,
         'TripUrl':None
      },
      {  
         'Id':'FR',
         'Name':'France',
         'DirectPrice':545,
         'IndirectPrice':418,
         'TripUrl':None
      },
      {  
         'Id':'UK',
         'Name':'United Kingdom',
         'DirectPrice':511,
         'IndirectPrice':484,
         'TripUrl':None
      },
      {  
         'Id':'BY',
         'Name':'Belarus',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CZ',
         'Name':'Czech Republic',
         'DirectPrice':555,
         'IndirectPrice':481,
         'TripUrl':None
      },
      {  
         'Id':'DE',
         'Name':'Germany',
         'DirectPrice':504,
         'IndirectPrice':431,
         'TripUrl':None
      },
      {  
         'Id':'BJ',
         'Name':'Benin',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CF',
         'Name':'Central African Republic',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KE',
         'Name':'Kenya',
         'IndirectPrice':706,
         'TripUrl':None
      },
      {  
         'Id':'BI',
         'Name':'Burundi',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BF',
         'Name':'Burkina Faso',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KM',
         'Name':'Comoros',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'ZM',
         'Name':'Zambia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SA',
         'Name':'Saudi Arabia',
         'IndirectPrice':813,
         'TripUrl':None
      },
      {  
         'Id':'BH',
         'Name':'Bahrain',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'JO',
         'Name':'Jordan',
         'IndirectPrice':1101,
         'TripUrl':None
      },
      {  
         'Id':'LA',
         'Name':'Laos',
         'IndirectPrice':248,
         'TripUrl':None
      },
      {  
         'Id':'BN',
         'Name':'Brunei',
         'DirectPrice':0,
         'IndirectPrice':653,
         'TripUrl':None
      },
      {  
         'Id':'BW',
         'Name':'Botswana',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CD',
         'Name':'DR Congo',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CM',
         'Name':'Cameroon',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'ZW',
         'Name':'Zimbabwe',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'RW',
         'Name':'Rwanda',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'ML',
         'Name':'Mali',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SO',
         'Name':'Somalia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MR',
         'Name':'Mauritania',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SL',
         'Name':'Sierra Leone',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'DJ',
         'Name':'Djibouti',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AO',
         'Name':'Angola',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CI',
         'Name':'Ivory Coast',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CG',
         'Name':'Congo',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GQ',
         'Name':'Equatorial Guinea',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GA',
         'Name':'Gabon',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'ER',
         'Name':'Eritrea',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GM',
         'Name':'Gambia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GN',
         'Name':'Guinea',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GH',
         'Name':'Ghana',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'DZ',
         'Name':'Algeria',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KW',
         'Name':'Kuwait',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'OM',
         'Name':'Oman',
         'IndirectPrice':876,
         'TripUrl':None
      },
      {  
         'Id':'PY',
         'Name':'Paraguay',
         'IndirectPrice':726,
         'TripUrl':None
      },
      {  
         'Id':'GF',
         'Name':'French Guiana',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'PE',
         'Name':'Peru',
         'IndirectPrice':637,
         'TripUrl':None
      },
      {  
         'Id':'CO',
         'Name':'Colombia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CK',
         'Name':'Cook Islands',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'NC',
         'Name':'New Caledonia',
         'IndirectPrice':992,
         'TripUrl':None
      },
      {  
         'Id':'AR',
         'Name':'Argentina',
         'IndirectPrice':721,
         'TripUrl':None
      },
      {  
         'Id':'VE',
         'Name':'Venezuela',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'IS',
         'Name':'Iceland',
         'IndirectPrice':613,
         'TripUrl':None
      },
      {  
         'Id':'SR',
         'Name':'Suriname',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'EC',
         'Name':'Ecuador',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CL',
         'Name':'Chile',
         'IndirectPrice':659,
         'TripUrl':None
      },
      {  
         'Id':'BO',
         'Name':'Bolivia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'UY',
         'Name':'Uruguay',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'FJ',
         'Name':'Fiji',
         'DirectPrice':0,
         'IndirectPrice':757,
         'TripUrl':None
      },
      {  
         'Id':'BM',
         'Name':'Bermuda',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CY',
         'Name':'Cyprus',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'LB',
         'Name':'Lebanon',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'IQ',
         'Name':'Iraq',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'PG',
         'Name':'Papua New Guinea',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AS',
         'Name':'American Samoa',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MP',
         'Name':'Northern Mariana Islands',
         'DirectPrice':338,
         'TripUrl':None
      },
      {  
         'Id':'VU',
         'Name':'Vanuatu',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MW',
         'Name':'Malawi',
         'IndirectPrice':746,
         'TripUrl':None
      },
      {  
         'Id':'MZ',
         'Name':'Mozambique',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AG',
         'Name':'Antigua and Barbuda',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GD',
         'Name':'Grenada',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'PR',
         'Name':'Puerto Rico',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'HN',
         'Name':'Honduras',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GT',
         'Name':'Guatemala',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'HT',
         'Name':'Haiti',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'DO',
         'Name':'Dominican Republic',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SX',
         'Name':'St Maarten',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'VI',
         'Name':'US Virgin Islands',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'NI',
         'Name':'Nicaragua',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'LC',
         'Name':'Saint Lucia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'ME',
         'Name':'Montenegro',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MK',
         'Name':'North Macedonia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KN',
         'Name':'Saint Kitts and Nevis',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BZ',
         'Name':'Belize',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BS',
         'Name':'Bahamas',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BQ',
         'Name':'Caribbean Netherlands',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TT',
         'Name':'Trinidad and Tobago',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AW',
         'Name':'Aruba',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KY',
         'Name':'Cayman Islands',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BB',
         'Name':'Barbados',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TC',
         'Name':'Turks and Caicos Islands',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GP',
         'Name':'Guadeloupe',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CW',
         'Name':'Curacao',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KG',
         'Name':'Kyrgyzstan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TJ',
         'Name':'Tajikistan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TM',
         'Name':'Turkmenistan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AZ',
         'Name':'Azerbaijan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BD',
         'Name':'Bangladesh',
         'IndirectPrice':599,
         'TripUrl':None
      },
      {  
         'Id':'NP',
         'Name':'Nepal',
         'DirectPrice':739,
         'TripUrl':None
      },
      {  
         'Id':'CR',
         'Name':'Costa Rica',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'JM',
         'Name':'Jamaica',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SV',
         'Name':'El Salvador',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'GI',
         'Name':'Gibraltar',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MQ',
         'Name':'Martinique',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AM',
         'Name':'Armenia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'AF',
         'Name':'Afghanistan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MG',
         'Name':'Madagascar',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TN',
         'Name':'Tunisia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'LU',
         'Name':'Luxembourg',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'PT',
         'Name':'Portugal',
         'IndirectPrice':523,
         'TripUrl':None
      },
      {  
         'Id':'EE',
         'Name':'Estonia',
         'IndirectPrice':608,
         'TripUrl':None
      },
      {  
         'Id':'RO',
         'Name':'Romania',
         'IndirectPrice':546,
         'TripUrl':None
      },
      {  
         'Id':'TZ',
         'Name':'Tanzania',
         'IndirectPrice':593,
         'TripUrl':None
      },
      {  
         'Id':'AL',
         'Name':'Albania',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'NA',
         'Name':'Namibia',
         'IndirectPrice':862,
         'TripUrl':None
      },
      {  
         'Id':'NE',
         'Name':'Niger',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'NG',
         'Name':'Nigeria',
         'IndirectPrice':897,
         'TripUrl':None
      },
      {  
         'Id':'SD',
         'Name':'Sudan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SC',
         'Name':'Seychelles',
         'IndirectPrice':868,
         'TripUrl':None
      },
      {  
         'Id':'RE',
         'Name':'Reunion',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TD',
         'Name':'Chad',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SN',
         'Name':'Senegal',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'TG',
         'Name':'Togo',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MA',
         'Name':'Morocco',
         'IndirectPrice':559,
         'TripUrl':None
      },
      {  
         'Id':'UG',
         'Name':'Uganda',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'RS',
         'Name':'Serbia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BA',
         'Name':'Bosnia and Herzegovina',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'KO',
         'Name':'Kosovo',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'MD',
         'Name':'Moldova',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'HR',
         'Name':'Croatia',
         'IndirectPrice':536,
         'TripUrl':None
      },
      {  
         'Id':'MT',
         'Name':'Malta',
         'IndirectPrice':459,
         'TripUrl':None
      },
      {  
         'Id':'IE',
         'Name':'Ireland',
         'IndirectPrice':458,
         'TripUrl':None
      },
      {  
         'Id':'NO',
         'Name':'Norway',
         'IndirectPrice':545,
         'TripUrl':None
      },
      {  
         'Id':'LV',
         'Name':'Latvia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'BG',
         'Name':'Bulgaria',
         'IndirectPrice':746,
         'TripUrl':None
      },
      {  
         'Id':'UA',
         'Name':'Ukraine',
         'IndirectPrice':1193,
         'TripUrl':None
      },
      {  
         'Id':'LT',
         'Name':'Lithuania',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SI',
         'Name':'Slovenia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SK',
         'Name':'Slovakia',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'SS',
         'Name':'South Sudan',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'CE',
         'Name':'Crimea',
         'IndirectPrice':0,
         'TripUrl':None
      },
      {  
         'Id':'WS',
         'Name':'Samoa',
         'IndirectPrice':1481,
         'TripUrl':None
      }
   ],
   'Metadata':{  
      'MachineName':'IP-0A346783',
      'Revision':'1.0.3172.0',
      'PriceSourceId':'taps-taps',
      'ExperimentAssignments':[  

      ],
      'Properties':[  
         {  
            'Name':'Browse Service All Results',
            'Value':192
         },
         {  
            'Name':'Browse Service Average Quote Age',
            'Value':302961
         },
         {  
            'Name':'Browse Service Node',
            'Value':'IP-0A346783'
         },
         {  
            'Name':'Browse Service Priced Results',
            'Value':87
         },
         {  
            'Name':'Browse Service Search Duration',
            'Value':89.4092
         },
         {  
            'Name':'Browse Service Version',
            'Value':'1.0.3172.0'
         },
         {  
            'Name':'Browse Service Zone',
            'Value':'Unknown'
         }
      ]
   }
}'''

pdata = data.replace("'",'"')
print(pdata)


# with open('../Ticketprice1112.json', 'w') as jsonfile:
#     json.dump(pdata, jsonfile, ensure_ascii=False)

# print('--- Ticketprice1112.json saved ---')
